<?php

/**
 * Implements hook_entity_type_build().
 *
 *  If the default add to cart form lacks some necessary functionality,
 *  you can either use a form alter hook or consider this cleaner approach:
 *
 *  Extend commerce_cart\Form\AddToCartForm.php
 *  Override any methods to alter the form functionality.
 *  Implement hook_entity_type_build() to swap out the default form with your custom one.
 *
 *  If your custom module name does not come after commerce_cart alphabetically,
 *  then you will need to manually adjust its weight.
 *  To do this, you can use hook_module_implements_alter()
 */
function custom_commerce_cart_entity_type_build(array &$entity_types) {
  $entity_types['commerce_order_item']->setFormClass('add_to_cart', '\Drupal\custom_commerce_cart\Form\CustomAddToCartForm');
}

/**
 * Implements hook_commerce_cart_order_convert().
 */
//function custom_commerce_cart_commerce_cart_order_convert($order_wrapper, $account) {
//  // custom logic to determine if order exists.
//  $order_wrapper->uid = 0;
//}
